![openclassrooms](https://s3.eu-west-1.amazonaws.com/course.oc-static.com/courses/6204541/1+HnqdJ-5ofxiPP9HIxdNdpw.jpeg)
# Create Your First Arrays Using NumPy
Throughout this course, you’re going to be playing the role of someone who works in the data team within a bank. More specifically, you work in the loans department. Your aim is to use your new-found Python libraries knowledge to help the team with various tasks.

For your first task, we've provided you with income levels for 10 of our bank’s customers. You’ll use the various data manipulation techniques in this chapter to select customer income levels based on specific conditions and perform certain operations.


In [ ]:
import numpy as np

Let’s look at the following monthly income figures:

In [ ]:
list = [1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300]

Based on this income data, create an array that you’ll name `income`:

In [ ]:
income = np.array(list)
display(income)

array([1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300])

Now, create a new array called `high_income`, which will select all income levels greater than or equal to $3000 per month:

In [ ]:
high_income = income[income>=3000]
display(high_income)


array([3000, 5000])

Note that in Python, you can define your **thousands separator** as '_' (underscore) to make the number easier to understand, e.g., “1_000_000” rather than “1000000.”

In [ ]:
high_income = income[income>=3_000]
high_income

array([3000, 5000])

Now it’s time to calculate a few results:
* Firstly, calculate the sum of all **annual** income figures. Just as a reminder, the above income levels are monthly.
* Then calculate the average income of these 10 customers.


In [ ]:
# Calculating the sum

sum_monthly = income.sum()
sum_monthly

20672

In [ ]:
# Multiply by 12

sum_income = sum_monthly * 12
sum_income

248064

When you’re starting out, it’s a good idea to **break down** your code. Writing code in multiple lines and using intermediate variables to help you control the result of each command will help you avoid **errors** and increase **confidence** in your code to ensure that you **fully understand** what you’re learning.

Then you can start **condensing** your code, i.e., compressing it by writing several commands in just one line of code without using intermediate variables.

In [ ]:
# You can combine the two operations into a single line:

sum_income = income.sum() * 12
print("The sum of annual income levels is:", "$", sum_income)

The sum of annual income levels is: $ 248064


In some cases, the **order of operations** has no effect on the result

In [ ]:
# So, we could also have said:

sum_income = (income * 12).sum()
print("The sum of annual income levels is:", "$", sum_income)

The sum of annual income levels is: $ 248064


In general, we would display “big” numbers as $k or $m, as this makes them easier to read. Readers tend to find it easier to understand a ballpark figure, or a rounded-up figure, rather than an exact number.

In [ ]:
# Example:

sum_income_K = round(sum_income / 1000)
print("The sum of annual income levels is:", "$", sum_income_K, "k")

The sum of annual income levels is: $ 248 k


In [ ]:
# Or even:

print("The sum of annual income levels is around:", "$", 250, "k")

The sum of annual income levels is around: $ 250 k


In [ ]:
# Or perhaps:

sum_income_M = round(sum_income / 1_000_000,2)
print("The sum of annual income levels is:", "$", sum_income_M,  "m")

The sum of annual income levels is: $ 0.25 m


Let’s move on to the average income.

In [ ]:
average = income.mean()
print("The average monthly income is:", "$", average)

The average monthly income is: $ 2087.2


In [ ]:
# Or perhaps:
average = round(average)
print("The average monthly income is:", "$", average)

The average monthly income is: $ 2087


One of our customers (with a monthly income currently at $1400) has just told us that they’ve had a promotion.

As a result, they now earn an additional $200 on top of their current monthly salary. Apply this update to your income array.

In [ ]:
print("Array before:", income)

income[income == 1400] = 1600
print("Array after:", income)

Array before: [1800 1500 2200 3000 2172 5000 1600 1200 1100 1300]
Array after: [1800 1500 2200 3000 2172 5000 1600 1200 1100 1300]


The update has been applied.

Let’s break this code down a bit more:

* `income[income == 1400]` selects all elements that are exactly equal to $1400 (which, in this case, is the only one we’re interested in).
* And the next bit updates the element with the new value (in our case, 1600).

In this line of code, we could also have used the ’+=’ operator to give `income[income == 1400] += 200`