![openclassrooms](https://s3.eu-west-1.amazonaws.com/course.oc-static.com/courses/6204541/1+HnqdJ-5ofxiPP9HIxdNdpw.jpeg)
# Transform Your Data Into Tables
For this second task, we’ll continue working with these 10 customers, but this time we have three data items available for each:
- Monthly income
- Customer age
- Number of children

Your objective is to use this information to create a NumPy table and respond to various requests from the loans department by manipulating the table using the techniques we’ve shown you throughout this chapter.


In [10]:
import numpy as np

All of this data is contained in the following list, called `table`:

In [2]:
hugh = [1800, 21, 0]
richard = [1500, 54, 2]
emily = [2200, 28, 3]
peter = [3000, 37, 1]
paul = [2172, 37, 2]
deborah = [5000, 32, 0]
john = [1400, 23, 0]
anne = [1200, 25, 1]
tom = [1100, 19, 0]
edward = [1300, 31, 2]

table = [hugh, richard, emily, peter, paul, deborah,
           john, anne, tom, edward]

display(table)

[[1800, 21, 0],
 [1500, 54, 2],
 [2200, 28, 3],
 [3000, 37, 1],
 [2172, 37, 2],
 [5000, 32, 0],
 [1400, 23, 0],
 [1200, 25, 1],
 [1100, 19, 0],
 [1300, 31, 2]]

Use this list to create an array called data

In [26]:
data = np.array(table)

Paul would like to take out a real estate loan:

- Display the information that relates to him. As a reminder, Paul’s data is shown in the fifth row of data.
- Calculate his maximum monthly repayment amount based on the fact that the maximum debt-to-income ratio is 35% (meaning that his monthly repayment amount cannot be more than 35% of his monthly income).


In [28]:
print("Data for Paul:")
print(data[4, :])
print("-")
print("His maximum repayment amount is:", round(data[4,0]*0.35, 2), "dollars")

Data for Paul:
[2172   37    2]
-
His maximum repayment amount is: 760.2 dollars


Because Paul is our fifth customer, we’ll find his data at integer position 4. Initially, we want to access all of his details (all variables), so we can use the : operator. Then, to do a calculation based on his income, we only access the relevant column.

In [30]:
louise = [1900, 31, 1]

Add this information to the end of your data array:

In [31]:
np.vstack((data, louise))

array([[1800,   21,    0],
       [1500,   54,    2],
       [2200,   28,    3],
       [3000,   37,    1],
       [2172,   37,    2],
       [5000,   32,    0],
       [1400,   23,    0],
       [1200,   25,    1],
       [1100,   19,    0],
       [1300,   31,    2],
       [1900,   31,    1]])

Store all data relating to customer salary in a variable called income:

In [33]:
income = data[:, 0]
print(income)

[1800 1500 2200 3000 2172 5000 1400 1200 1100 1300]


Well done!
As always, you’ll find our suggested answer in full in the solution, so you can use it to check your work or understand anything you weren’t sure about: [link to solution](https://colab.research.google.com/github/OpenClassrooms-Student-Center/en-8253136-Use-Python-Libraries-for-Data-Science/blob/main/notebooks/P1/P1C4%20-%20Transform%20Your%20Data%20Into%20Tables%20-%20CORRECTION.ipynb).
